language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install scipy
  - pip install pybuilder
  - pip install coveralls

script:
  - pyb

after_success:
  - coveralls --verbose

