language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install pybuilder
  - pip install coveralls

script:
  - pyb

after_success:
  - coveralls --verbose

