# ----------------------- #
#     Site Variables      #
# ----------------------- #

name: DiceRV
author: Peleg M
url: 'http://peleg.github.io/dicerv'

title: "DiceRV"
subtitle: "Dice Random Variables Made Easy"

github_url: https://github.com/pelegm/dicerv
github_username: pelegm

## TODO
github_license: The MIT License
github_license_url: https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md


# ----------------------- #
#       Site Paths        #
# ----------------------- #

# LOCAL
stylesheets: /assets/stylesheets
javascripts: /assets/javascripts
images:      /assets/images
fonts:       /assets/fonts

# GLOBAL
global_stylesheets: http://pelegm.github.io/dicerv/assets/stylesheets
global_javascripts: http://pelegm.github.io/dicerv/assets/javascripts
global_images:      http://pelegm.github.io/dicerv/assets/images
global_fonts:       http://pelegm.github.io/dicerv/assets/fonts

# ----------------------- #
#     Plugin Configs      #
# ----------------------- #

# google_analytics_id:   UA-44446017-1
# google_analytics_name: iqandreas.com

# source_title_prefix: "GitHub: IQAndreas/gh-pages-template"
# source_url: 'https://github.com/IQAndreas/gh-pages-template/tree/gh-pages'

# ----------------------- #
#     Jekyll Configs      #
# ----------------------- #

#source: source
destination: _public
plugins: 	 _plugins

exclude: [LICENSE.md]

relative_permalinks: false
markdown: redcarpet
pygments: true

