# Site settings
title: DiceRV
email: your-email@domain.com
description: "Dice Random Variables Made Easy"
baseurl: "/dicerv"
url: "http://pelegm.github.io/dicerv"
# twitter_username: jeky
github_username:  pelegm

# Build settings
markdown: kramdown
permalink: pretty
